# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'file_dialoge.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_File_dialoge(object):
    def setupUi(self, File_dialoge):
        File_dialoge.setObjectName("File_dialoge")
        File_dialoge.resize(880, 576)
        self.label = QtWidgets.QLabel(File_dialoge)
        self.label.setGeometry(QtCore.QRect(40, 42, 91, 16))
        self.label.setObjectName("label")
        self.search = QtWidgets.QPushButton(File_dialoge)
        self.search.setGeometry(QtCore.QRect(660, 30, 93, 51))
        self.search.setObjectName("search")
        self.select = QtWidgets.QPushButton(File_dialoge)
        self.select.setGeometry(QtCore.QRect(505, 37, 131, 28))
        self.select.setObjectName("select")
        self.table = QtWidgets.QTableWidget(File_dialoge)
        self.table.setGeometry(QtCore.QRect(30, 80, 611, 461))
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.labelWrite = QtWidgets.QPushButton(File_dialoge)
        self.labelWrite.setGeometry(QtCore.QRect(770, 30, 93, 51))
        self.labelWrite.setObjectName("labelWrite")
        self.path = QtWidgets.QLineEdit(File_dialoge)
        self.path.setGeometry(QtCore.QRect(130, 40, 361, 21))
        self.path.setObjectName("path")
        self.warning = QtWidgets.QLabel(File_dialoge)
        self.warning.setGeometry(QtCore.QRect(480, 20, 190, 16))
        self.warning.setAlignment(QtCore.Qt.AlignCenter)
        self.warning.setText("")
        self.warning.setObjectName("warning")
        self.goToSetting = QtWidgets.QPushButton(File_dialoge)
        self.goToSetting.setGeometry(QtCore.QRect(10, 7, 93, 28))
        self.goToSetting.setObjectName("goToSetting")
        self.label_2 = QtWidgets.QLabel(File_dialoge)
        self.label_2.setGeometry(QtCore.QRect(724, 130, 72, 15))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.labelSelect = QtWidgets.QComboBox(File_dialoge)
        self.labelSelect.setGeometry(QtCore.QRect(701, 160, 121, 22))
        self.labelSelect.setObjectName("labelSelect")
        self.label_3 = QtWidgets.QLabel(File_dialoge)
        self.label_3.setGeometry(QtCore.QRect(714, 230, 90, 15))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.nozomi = QtWidgets.QLineEdit(File_dialoge)
        self.nozomi.setGeometry(QtCore.QRect(703, 260, 113, 21))
        self.nozomi.setObjectName("nozomi")
        self.sort = QtWidgets.QPushButton(File_dialoge)
        self.sort.setGeometry(QtCore.QRect(715, 330, 93, 51))
        self.sort.setObjectName("sort")
        self.exit = QtWidgets.QPushButton(File_dialoge)
        self.exit.setGeometry(QtCore.QRect(700, 430, 121, 101))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.exit.setFont(font)
        self.exit.setIconSize(QtCore.QSize(42, 42))
        self.exit.setObjectName("exit")

        self.retranslateUi(File_dialoge)
        QtCore.QMetaObject.connectSlotsByName(File_dialoge)

    def retranslateUi(self, File_dialoge):
        _translate = QtCore.QCoreApplication.translate
        File_dialoge.setWindowTitle(_translate("File_dialoge", "Form"))
        self.label.setText(_translate("File_dialoge", "Path: "))
        self.search.setText(_translate("File_dialoge", "Scan"))
        self.select.setText(_translate("File_dialoge", "Select folder"))
        self.labelWrite.setText(_translate("File_dialoge", "Record"))
        self.goToSetting.setText(_translate("File_dialoge", "Setting"))
        self.label_2.setText(_translate("File_dialoge", "Label"))
        self.label_3.setText(_translate("File_dialoge", "Expectation"))
        self.sort.setText(_translate("File_dialoge", "Reorder"))
        self.exit.setText(_translate("File_dialoge", "Exit"))
